image: node:16.13.1

definitions:
  pushrepo: &pushrepo
    name: Push to VRC DevOps
    script:
      - apt-get update
      - apt-get install openssh-client -y
      - git fetch --unshallow origin
      - git remote set-url origin $DEVOPS_REPO
      - git checkout -B $BITBUCKET_BRANCH
      - git config user.name "Conduct Bitbucket"
      - git config user.email "dev@conducthq.com"
      - git push origin $BITBUCKET_BRANCH
  caches:
    yarn: /usr/local/share/.cache/yarn
  scripts:
    - script: &configureDotEnv touch .env;
        echo "REACT_APP_FE_BASE_URL=$REACT_APP_FE_BASE_URL" >> .env;
        echo "REACT_APP_AZURE_B2C_TENANT=$REACT_APP_AZURE_B2C_TENANT" >> .env;
        echo "REACT_APP_AZURE_B2C_CLIENT_ID=$REACT_APP_AZURE_B2C_CLIENT_ID" >> .env;

stepdefinitions:
  test: &test
    name: Test Project
    caches:
      - node
      - yarn
    script:
      - yarn install
      - yarn test --passWithNoTests

pipelines:
  default:
    - step: *test
  branches:
    development:
      - step: *test
      - step:
          name: Build Project, Deploy and Purge CDN
          deployment: development
          image: node:16.13.1
          caches:
            - node
            - yarn
          script:
            - *configureDotEnv
            - yarn install
            - yarn build
            - pipe: microsoft/azure-storage-deploy:2.0.1
              variables:
                SOURCE: 'build/**'
                DESTINATION: '$AZURE_STORAGE_URL'
                DESTINATION_SAS_TOKEN: '$AZURE_STORAGE_SAS_TOKEN'
                EXTRA_ARGS: '--recursive'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az storage blob service-properties update --account-name $AZURE_WEB_STORAGE_NAME --static-website --index-document index.html --404-document index.html'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az cdn endpoint rule remove --resource-group $AZURE_RESOURCE_GROUP --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --rule-name RewriteSpaRoutes'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az cdn endpoint rule remove --resource-group $AZURE_RESOURCE_GROUP --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --rule-name HttpToHttps'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az cdn endpoint rule add --resource-group $AZURE_RESOURCE_GROUP --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --order 1 --rule-name HttpToHttps --match-variable RequestScheme --operator Equal --match-values HTTP --action-name UrlRedirect --redirect-protocol Https --redirect-type Moved'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az cdn endpoint rule add --resource-group $AZURE_RESOURCE_GROUP --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --order 2 --rule-name RewriteSpaRoutes --match-variable UrlFileExtension --operator LessThan --match-values 1 --action-name UrlRewrite --source-pattern / --destination /index.html --preserve-unmatched-path false'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az cdn endpoint purge --resource-group $AZURE_RESOURCE_GROUP --profile-name $AZURE_CDN_PROFILE --name $AZURE_CDN_ENDPOINT --content-paths /*'
                DEBUG: 'true'
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                CLI_COMMAND: 'az functionapp cors add --name $AZURE_FUNCTION_APP_NAME --resource-group $AZURE_RESOURCE_GROUP --allowed-origins $REACT_APP_FE_BASE_URL'
                DEBUG: 'true'

    client-dev:
      - step: *pushrepo

    staging:
      - step: *pushrepo